### ISSUE TITLE
Compilation warning on OSX

### ISSUE THREAD

**Issue by grrussel** [olleolleolle/wav2c#3]
Family-iMac:wav2c-master grrussel$ make
gcc -c main.c
gcc -c wavdata.c
wavdata.c:59:6: warning: implicitly declaring library function 'strcmp' with
      type 'int (const char *, const char *)'
        if (strcmp(c, "RIFF") != 0) {
            ^
wavdata.c:59:6: note: include the header <string.h> or explicitly provide a
      declaration for 'strcmp'
1 warning generated.
gcc main.o wavdata.o -o wav2c

**Comment by olleolleolle** [comment]
Dear @grrussel, does this fix do it for you?
